---
- name: Fetch rustup
  uri:
    url: https://sh.rustup.rs
    return_content: yes
  register: rustup_installer

- name: Run rustup Installer
  shell:
    cmd: sh -s -- -y --profile default
    stding: "{{ rustup_installer.content }}"

- name: Install rust-analyzer
  become_user: root
  pacman:
    name: rust-analyzer
    state: present
