---
- hosts: localhost
  become: true

  collections:
    - community.general
  roles:
    - { role: base, tags: ["base"] }
    - { role: video-drivers, tags: ["video-drivers"] }
    - { role: xorg, tags: ["xorg"] }
    - { role: aur, tags: ["aur"] }
    - { role: bspwm, tags: ["bspwm"], become_user: "{{ username }}" }
  vars_prompt:
    - name: username
      prompt: "Enter username: "
      private: no
    - name: password
      prompt: "Enter password: "
      unsafe: yes
      private: yes
