---
- aur:
    name: polybar
    use: yay
    state: present
    tags:
      - yay

- name: Create polybar config dir
  file:
    path: ~/.config/polybar
    state: directory

- name: Copy polybar config
  copy:
    src: polybar
    dest: ~/.config/polybar/config
