---
- name: Install Rofi
  become_user: root
  pacman:
    name: rofi
    state: present

- name: Create rofi config dir
  file:
    path: ~/.config/rofi
    state: directory

- name: Copy rofi config file
  copy:
    src: rofi
    dest: ~/.config/rofi/config.rasi
