---
- name: Enable Pacman parallel downloads
  lineinfile:
    path: /etc/pacman.conf
    regexp: '^#?ParallelDownloads'
    line: 'ParallelDownloads = 5'

- name: Install base packages
  pacman:
    name: "{{ base_packages }}"
    state: present

- include: user.yml
- include: sudo.yml
