---
- name: Create User - {{ username }}
  user:
    name: "{{ username }}"
    password: "{{ password | password_hash('sha512') }}"
    update_password: on_create
    append: true
    create_home: true
    groups:
      - wheel
      - docker
    shell: "{{ user.shell }}"
    state: present
